# Generated by Django 6.0.5 on 2026-05-25 14:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFieldTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=255, verbose_name='CharField')),
                ('text_field', models.TextField(verbose_name='TextField')),
                ('slug_field', models.SlugField(max_length=255, unique=True)),
                ('email_field', models.EmailField(max_length=254, unique=True)),
                ('url_field', models.URLField()),
                ('generic_ip', models.GenericIPAddressField()),
                ('regex_field', models.CharField(help_text='Regex example', max_length=20)),
                ('integer_field', models.IntegerField()),
                ('positive_integer', models.PositiveIntegerField()),
                ('positive_small_integer', models.PositiveSmallIntegerField()),
                ('small_integer', models.SmallIntegerField()),
                ('big_integer', models.BigIntegerField()),
                ('float_field', models.FloatField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boolean_field', models.BooleanField(default=False)),
                ('date_field', models.DateField()),
                ('time_field', models.TimeField()),
                ('datetime_field', models.DateTimeField()),
                ('auto_now_field', models.DateTimeField(auto_now=True)),
                ('auto_now_add_field', models.DateTimeField(auto_now_add=True)),
                ('duration_field', models.DurationField()),
                ('file_field', models.FileField(upload_to='files/')),
                ('image_field', models.ImageField(upload_to='images/')),
                ('uuid_field', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('json_field', models.JSONField(default=dict)),
                ('binary_field', models.BinaryField(blank=True, null=True)),
                ('choices_field', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], max_length=20)),
                ('nullable_field', models.CharField(blank=True, max_length=255, null=True)),
                ('indexed_field', models.CharField(db_index=True, max_length=255)),
                ('unique_field', models.CharField(max_length=255, unique=True)),
                ('validated_integer', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_fields_fk', to=settings.AUTH_USER_MODEL)),
                ('friends', models.ManyToManyField(blank=True, to='tests.allfieldtypesmodel')),
                ('many_to_many', models.ManyToManyField(related_name='all_fields_m2m', to='auth.group')),
                ('one_to_one', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='all_fields_o2o', to=settings.AUTH_USER_MODEL)),
                ('self_relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tests.allfieldtypesmodel')),
            ],
            options={
                'verbose_name': 'All Field Types Model',
                'verbose_name_plural': 'All Field Types Models',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('tag', models.CharField(max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
